CREATE DATABASE IF NOT EXISTS catatan_github;
USE catatan_github;

CREATE TABLE catatan(
    id INT AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(255),
    isi TEXT,
    arsip BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
)